module Routing
  # Plans a camera-avoiding route. It builds a few candidate routes — the plain
  # fastest, an iterative-exclusion route, and a "quiet" route biased onto surface
  # streets — and always prefers one that passes NO camera at all (the fastest such,
  # whatever the detour costs). When no candidate is fully camera-free, it falls back
  # to minimum exposure rather than failing: the route minimising
  # `duration_s + λ · proximity_cost` under a detour cap. Proximity cost
  # (ProximityScorer) measures how *close* a route passes every nearby camera, not
  # just whether it drives the monitored segment — so a detour that technically
  # leaves the segment but still hugs a dozen cameras isn't mistaken for avoidance,
  # and a pathological out-of-the-way loop that barely lowers exposure is rejected.
  #
  # The exclusion candidate is generated by iteratively excluding the monitored
  # segments a route passes and rerouting (minimum exposure): far better than a single
  # all-segments-in-the-bbox exclusion, which over-constrains the graph and usually
  # fails outright. (Routing::Result lives in routing/result.rb for Zeitwerk.)
  class RoutePlanner
    BBOX_PADDING = 0.05 # degrees of padding around the O/D bounding box
    MAX_PASSES = 8 # cap on avoid/reroute iterations (== extra routing calls)
    # Per-pass cap on the one-at-a-time exclusion fallback (each is a Valhalla
    # reroute), so a camera-dense grid can't fan out into dozens of calls in a pass.
    FALLBACK_FANOUT_LIMIT = 8
    # Hard ceiling on how far out of the way we'll go in the minimum-exposure fallback
    # — the fastest route is always kept in the pool, so this only ever drops absurd
    # detours, never leaves us without a route. (A fully camera-free route is never
    # capped: max avoidance takes it whatever the detour.)
    MAX_DETOUR_RATIO = 3.0
    # km/h cap for the quiet candidate: flattening the speed advantage of arterials
    # (alongside use_highways: 0) pushes detours onto surface/residential streets
    # instead of a faster highway loop.
    QUIET_TOP_SPEED = 50
    # Single source of truth for the confidence floor below which a camera is not
    # avoided. Threaded into the candidate query so the avoided set is defined in one
    # place (the proximity scorer then scores exactly that candidate set).
    MIN_AVOID_CONFIDENCE = 0.0
    # Seconds of extra travel time we'll accept per unit of camera-proximity cost
    # removed (see ProximityScorer) in the minimum-exposure fallback — i.e. only when
    # no fully camera-free route exists. Calibrated from real Des Moines routes: high
    # enough to take worthwhile residential detours, low enough to reject pathological
    # loops that barely lower exposure.
    PROXIMITY_LAMBDA = 90.0
    # Overall monotonic budget (seconds) for route planning, including candidate
    # lookup and the mandatory fastest route. Database stages set a transaction-local
    # statement_timeout from the remaining budget; optional work returns the last
    # complete truthful result when the budget expires. A small scheduler or
    # serialization overrun is possible after a stage completes. Override with
    # ROUTE_DEADLINE_S.
    DEADLINE_S = Float(ENV.fetch("ROUTE_DEADLINE_S", 8.0))

    def initialize(routing_client: RoutingEngineClient.build,
                   exclusion_builder: SegmentExclusionBuilder.new,
                   detector: RouteCameraDetector.new,
                   proximity_scorer: ProximityScorer.new)
      @routing = routing_client
      @exclusion = exclusion_builder
      @detector = detector
      @proximity = proximity_scorer
    end

    def plan(origin:, destination:, locale: "en", deadline_s: DEADLINE_S)
      deadline = monotonic_now + deadline_s
      bbox = bounding_box(origin, destination)
      candidates = database_stage(deadline, mandatory: true) do
        @exclusion.segments_in_bbox(bbox, min_confidence: MIN_AVOID_CONFIDENCE)
      end
      raise Geo::HttpClient::ServiceError, "route planning deadline exceeded" unless candidates

      timeout = remaining_timeout(deadline)
      raise Geo::HttpClient::ServiceError, "route planning deadline exceeded" unless timeout

      fastest = @routing.route(origin: origin, destination: destination, timeout: timeout)
      raise Geo::HttpClient::ServiceError, "route planning deadline exceeded" if deadline_exceeded?(deadline)

      fastest_passed = detector_passed(fastest, candidates, deadline)
      raise Geo::HttpClient::ServiceError, "route planning deadline exceeded" unless fastest_passed
      chosen = choose_route(origin, destination, fastest, fastest_passed, candidates, deadline)
      chosen_passed = chosen.equal?(fastest) ? fastest_passed : detector_passed(chosen, candidates, deadline)
      # A detector timeout cannot leave fastest metadata attached to another route.
      chosen, chosen_passed = fastest, fastest_passed unless chosen_passed

      build_result(
        route: chosen,
        fastest: fastest,
        fastest_passed: fastest_passed,
        chosen_passed: chosen_passed,
        origin: origin,
        destination: destination,
        locale: locale,
        deadline: deadline
      )
    end

    private

    # Builds the candidate pool and selects a route. Always prefers a route that
    # passes NO camera at all — the fastest such, whatever the detour costs (max
    # avoidance is the only mode). When no candidate is fully clean, it falls back to
    # minimum exposure rather than failing: among non-absurd detours (within
    # MAX_DETOUR_RATIO of the fastest), the route minimising `duration_s + λ ·
    # proximity_cost`, so we pick the genuinely least-exposed route and not a
    # pathological loop. A fastest route that already passes no cameras short-circuits
    # to itself.
    def choose_route(origin, destination, fastest, fastest_passed, candidates, deadline)
      return fastest if fastest_passed.empty?

      pool = [ fastest ]
      exclusion = avoid(origin, destination, candidates, fastest, fastest_passed, deadline)
      pool << exclusion unless exclusion.equal?(fastest)
      # Skip the speculative quiet candidate once the budget is spent.
      quiet = deadline_exceeded?(deadline) ? nil : quiet_route(origin, destination, deadline)
      pool << quiet if quiet

      clean = pool.select { |route| detector_passed(route, candidates, deadline)&.empty? }
      return clean.min_by { |route| route[:duration_s].to_i } if clean.any?

      # No camera-free route exists — minimum exposure. Cap absurd detours; the
      # fastest route is always in the pool, so we never end up without a route.
      cap = fastest[:duration_s].to_i * MAX_DETOUR_RATIO
      pool.select! { |route| route.equal?(fastest) || route[:duration_s].to_i <= cap }
      scored = pool.filter_map do |route|
        cost = database_stage(deadline) { @proximity.cost(route, candidates) }
        cost ? [ route, route[:duration_s].to_i + PROXIMITY_LAMBDA * cost ] : nil
      end
      scored.min_by(&:last)&.first || fastest
    end

    # A route biased onto quieter surface streets (no highways + a low top speed), so
    # the selector has an out-of-the-way option that doesn't 442 the way a hard
    # exclusion can. nil when the engine can't produce one.
    def quiet_route(origin, destination, deadline)
      timeout = remaining_timeout(deadline)
      return nil unless timeout

      route = @routing.route(origin: origin, destination: destination,
                             costing_options: { use_highways: 0, top_speed: QUIET_TOP_SPEED },
                             timeout: timeout)
      deadline_exceeded?(deadline) ? nil : route
    rescue Geo::HttpClient::ServiceError
      nil
    end

    # Generates the iterative-exclusion candidate: excludes the monitored segments a
    # route passes and reroutes, keeping the lowest-on-segment route found, and returns
    # it (may be `fastest` if nothing better is feasible). `fastest_passed` is the
    # segments the fastest route passes (already computed by the caller).
    #
    # Each pass excludes every monitored segment the latest route passes (on top of
    # what's already excluded) and reroutes. A reroute may pass *different* segments,
    # so we loop until the route is clean, nothing new can be excluded, or no further
    # exclusion is feasible. We only ever keep a reroute as `best` when it passes
    # *fewer* cameras than the best so far — in a camera-dense grid, avoiding one
    # segment can route through several others.
    #
    # When excluding the whole passed set at once has no path, we do NOT give up
    # (that would silently hand back the fastest route through *every* camera).
    # Instead we exclude the passed segments one at a time, keeping whichever still
    # route — true minimum exposure. A segment that's infeasible even on its own is
    # genuinely unavoidable (e.g. the only road out), so we stop retrying it.
    def avoid(origin, destination, candidates, fastest, fastest_passed, deadline)
      best = fastest
      best_passed = fastest_passed
      excluded_ids = Set.new # segments excluded so far (feasible together)
      unavoidable = Set.new  # segments with no path even alone — stop retrying them
      current = fastest

      MAX_PASSES.times do
        break if deadline_exceeded?(deadline) # budget spent — return the best route found so far

        passed = detector_passed(current, candidates, deadline)
        break unless passed
        new_ids = passed.map(&:id) - excluded_ids.to_a - unavoidable.to_a
        break if new_ids.empty? # nothing left we can try to exclude — best effort reached

        route = reroute_excluding(origin, destination, candidates, excluded_ids.to_a + new_ids, deadline)

        if route
          excluded_ids.merge(new_ids)
          current = route
          best, best_passed = keep_lower_exposure(best, best_passed, current, candidates, deadline)
        elsif new_ids.one?
          # The lone newly-passed segment has no path when excluded: unavoidable.
          unavoidable << new_ids.first
        else
          # Excluding them all at once has no path — add them one at a time and keep
          # the feasible ones (minimum exposure) rather than abandoning avoidance.
          # Capped: each individual retry is a Valhalla reroute, so in a pathological
          # camera-dense grid we bound the per-pass fan-out rather than excluding
          # dozens one by one (the few we drop are picked up on the next pass).
          progressed = false
          new_ids.first(FALLBACK_FANOUT_LIMIT).each do |id|
            break if deadline_exceeded?(deadline) # bound the per-pass fan-out by the budget too

            trial = reroute_excluding(origin, destination, candidates, excluded_ids.to_a + [ id ], deadline)
            if trial
              excluded_ids << id
              current = trial
              best, best_passed = keep_lower_exposure(best, best_passed, current, candidates, deadline)
              progressed = true
              break if best_passed.empty?
            else
              unavoidable << id
            end
          end
          next unless progressed # nothing more excludable this pass — but later passes may differ
        end

        break if best_passed.empty? # found a fully clean route
      end

      best
    end

    # Reroutes excluding the given segment ids (pulled from candidates). nil when no
    # path exists under that exclusion set, or the set is empty.
    def reroute_excluding(origin, destination, candidates, ids, deadline)
      segments = candidates.select { |s| ids.include?(s.id) }
      rings = database_stage(deadline) { @exclusion.rings_for(segments) }
      rings ? safe_route(origin, destination, rings, deadline) : nil
    end

    # Keeps a candidate route as the new best only when it passes strictly fewer
    # cameras than the best so far. Returns [best, best_passed].
    def keep_lower_exposure(best, best_passed, candidate_route, candidates, deadline)
      passed = detector_passed(candidate_route, candidates, deadline)
      return [ best, best_passed ] unless passed
      passed.size < best_passed.size ? [ candidate_route, passed ] : [ best, best_passed ]
    end

    def safe_route(origin, destination, exclude_polygons, deadline)
      return nil if exclude_polygons.empty?

      timeout = remaining_timeout(deadline)
      return nil unless timeout

      route = @routing.route(origin: origin, destination: destination,
                             exclude_polygons: exclude_polygons, timeout: timeout)
      deadline_exceeded?(deadline) ? nil : route
    rescue Geo::HttpClient::ServiceError
      nil # no route under this exclusion set → caller keeps the best route so far
    end

    def build_result(route:, fastest:, fastest_passed:, chosen_passed:, origin:, destination:, locale:, deadline:)
      # Count distinct cameras, not monitored segments: a camera can own several
      # segments and several cameras can snap to one OSM way, so segment counts
      # would over-report. This keeps avoided/remaining/passed numbers consistent.
      fastest_cameras = fastest_passed.uniq(&:camera_id)
      chosen_cameras = chosen_passed.uniq(&:camera_id)

      Result.new(
        geometry: route[:geometry],
        distance_m: route[:distance_m],
        duration_s: route[:duration_s],
        maneuvers: ManeuverLocalizer.localize(route[:maneuvers], locale: locale),
        # How many fewer cameras the chosen route drives past than the fastest one
        # (>= 0). The selector can pick a route on proximity grounds that isn't the
        # strict minimum, so clamp rather than report a negative.
        cameras_avoided_count: [ fastest_cameras.size - chosen_cameras.size, 0 ].max,
        remaining_cameras: chosen_cameras.map { |seg| { osm_way_id: seg.osm_way_id } },
        is_fully_clean: chosen_passed.empty?,
        fastest_comparison: comparison(route, fastest, fastest_cameras.size),
        coverage_warning: coverage_warning(origin, destination, deadline)
      )
    end

    # The fastest (non-avoiding) route, surfaced so the frontend can draw it as a
    # comparison line and show what avoidance costs. `geometry` lets the client
    # draw the second line; `cameras_passed_count` is how many cameras the fastest
    # route passes, so the UI can show it is not camera-free.
    def comparison(route, fastest, fastest_cameras_count)
      {
        distance_m: fastest[:distance_m],
        duration_s: fastest[:duration_s],
        # Distance is independent of time, so an avoiding route can be shorter than
        # the time-fastest one; clamp so we never report negative "extra distance".
        added_distance_m: [ route[:distance_m].to_i - fastest[:distance_m].to_i, 0 ].max,
        added_duration_s: route[:duration_s].to_i - fastest[:duration_s].to_i,
        geometry: fastest[:geometry],
        cameras_passed_count: fastest_cameras_count
      }
    end

    def coverage_warning(origin, destination, deadline)
      covered = database_stage(deadline) do
        CoverageArea.covers?(origin[:lng], origin[:lat]) &&
          CoverageArea.covers?(destination[:lng], destination[:lat])
      end
      return nil if covered.nil?

      covered ? nil : "outside_coverage"
    end

    def detector_passed(route, candidates, deadline)
      database_stage(deadline) { @detector.passed(route, candidates) }
    end

    # SET LOCAL is scoped to this transaction. A cancelled query rolls back only
    # this isolated transaction, so later fallback stages get a clean connection.
    def database_stage(deadline, mandatory: false)
      timeout = remaining_timeout(deadline)
      return nil unless timeout

      milliseconds = [ (timeout * 1000).ceil, 1 ].max
      ActiveRecord::Base.transaction(requires_new: true) do
        timeout = ActiveRecord::Relation::QueryAttribute.new(
          "statement_timeout", "#{milliseconds}ms", ActiveRecord::Type::String.new
        )
        ActiveRecord::Base.connection.exec_query(
          "SELECT set_config('statement_timeout', $1, true)", "set statement timeout", [ timeout ]
        )
        yield
      end
    rescue ActiveRecord::QueryCanceled
      raise Geo::HttpClient::ServiceError, "route planning deadline exceeded" if mandatory

      nil
    end

    # Uses a monotonic clock so wall-clock adjustments cannot extend the budget.
    # A non-positive remainder is never passed to the HTTP client, where zero would
    # otherwise disable rather than constrain some timeout implementations.
    def remaining_timeout(deadline)
      remaining = deadline - monotonic_now
      remaining.positive? ? remaining : nil
    end

    def deadline_exceeded?(deadline)
      remaining_timeout(deadline).nil?
    end

    def monotonic_now
      Process.clock_gettime(Process::CLOCK_MONOTONIC)
    end

    def bounding_box(origin, destination)
      lngs = [ origin[:lng], destination[:lng] ]
      lats = [ origin[:lat], destination[:lat] ]
      [
        lngs.min - BBOX_PADDING, lats.min - BBOX_PADDING,
        lngs.max + BBOX_PADDING, lats.max + BBOX_PADDING
      ]
    end
  end
end
