/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan a camera-avoiding driving route
         * @description Returns a drivable route avoiding all monitored segments when possible (FR-003); otherwise a minimum-exposure route flagged is_fully_clean=false (FR-004). Coordinates are processed in-memory and excluded from logs (FR-011).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RouteRequest"];
                };
            };
            responses: {
                /** @description A planned route */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Route"];
                    };
                };
                400: components["responses"]["Error"];
                /** @description No usable route. code=no_route when no drivable route exists between the points. Note: camera avoidance never fails — when no fully camera-free route exists the planner returns the fewest-cameras route with is_fully_clean=false (200), not an error. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                429: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geocode/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Forward geocode / address autocomplete
         * @description Text place search for origin/destination entry and disambiguation (FR-001, FR-016).
         */
        get: {
            parameters: {
                query: {
                    q: string;
                    lang?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ranked matches */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            results?: components["schemas"]["GeocodeResult"][];
                        };
                    };
                };
                400: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geocode/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reverse geocode a coordinate
         * @description Used when the user shares device location for the origin (FR-001). POST keeps the coordinate out of URLs/logs.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Coordinate"];
                };
            };
            responses: {
                /** @description Nearest matching place */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GeocodeResult"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List known cameras within a viewport
         * @description Reference data for display (US4). Returns camera reference points only — never user data. Bounded by a bounding box to keep responses small.
         */
        get: {
            parameters: {
                query: {
                    /** @description minLng,minLat,maxLng,maxLat */
                    bbox: string;
                    min_confidence?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cameras in the bbox */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            cameras?: components["schemas"]["Camera"][];
                        };
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check camera-data coverage for a point
         * @description Tells the client whether avoidance is available and how fresh the data is (FR-018).
         */
        get: {
            parameters: {
                query: {
                    lat: number;
                    lng: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Coverage status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            covered?: boolean;
                            area_name?: string | null;
                            /** Format: date-time */
                            data_freshness_at?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/locales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List supported interface languages
         * @description Drives the language switcher (FR-013).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Supported locales */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            default?: string;
                            locales?: {
                                code?: string;
                                name?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Coordinate: {
            lat: number;
            lng: number;
        };
        RouteRequest: {
            origin: components["schemas"]["Coordinate"];
            destination: components["schemas"]["Coordinate"];
            /**
             * @description BCP-47
             * @default en
             */
            locale: string;
        };
        Maneuver: {
            /** @description provider-neutral maneuver type */
            type?: string;
            localized_text?: string;
            distance_m?: number;
            /** @description index into the route polyline where the maneuver begins */
            shape_index?: number;
        };
        RemainingCamera: {
            location?: components["schemas"]["Coordinate"];
            /** Format: int64 */
            osm_way_id?: number;
        };
        FastestComparison: {
            distance_m?: number;
            duration_s?: number;
            added_distance_m?: number;
            added_duration_s?: number;
            /** @description Encoded polyline (precision 6) of the fastest non-avoiding route, for drawing the comparison line. */
            geometry?: string;
            /** @description Number of monitored camera segments the fastest route would pass. */
            cameras_passed_count?: number;
        };
        Route: {
            /** @description encoded polyline */
            geometry?: string;
            distance_m?: number;
            duration_s?: number;
            maneuvers?: components["schemas"]["Maneuver"][];
            cameras_avoided_count?: number;
            remaining_cameras?: components["schemas"]["RemainingCamera"][];
            is_fully_clean?: boolean;
            fastest_comparison?: components["schemas"]["FastestComparison"];
            /** @enum {string|null} */
            coverage_warning?: "outside_coverage" | "stale_data" | "partial_coverage" | null;
        };
        GeocodeResult: {
            label?: string;
            lat?: number;
            lng?: number;
            type?: string;
            confidence?: number;
        };
        Camera: {
            /** Format: int64 */
            id?: number;
            location?: components["schemas"]["Coordinate"];
            /** @description Camera point snapped onto its monitored road segment; null until the camera is snapped. */
            snapped_location?: {
                lat?: number;
                lng?: number;
            } | null;
            /** @description Monitored-segment geometry as [lng, lat] pairs; null until the camera is snapped. */
            segment?: number[][] | null;
            /** @description Compass bearing the camera faces (0–359); null for omnidirectional / 360°. */
            facing_direction?: number | null;
            camera_type?: string | null;
            confidence?: number;
            /** @enum {string} */
            verification_status?: "unverified" | "verified" | "disputed" | "removed";
        };
        Error: {
            /** @description stable machine code (e.g. */
            code: string;
            /** @description human-readable */
            message: string;
            details?: {
                [key: string]: unknown;
            } | null;
        };
    };
    responses: {
        /** @description A structured, localized, actionable error (Constitution Principle III) */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
